/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.yaaic.client;

public final class R {
    public static final class array {
        public static final int server_popup=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int add=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int settings=0x7f020002;
    }
    public static final class id {
        public static final int about=0x7f08000b;
        public static final int server_add=0x7f080006;
        public static final int server_autoconnect=0x7f080004;
        public static final int server_channels=0x7f080007;
        public static final int server_host=0x7f080001;
        public static final int server_input=0x7f080009;
        public static final int server_log=0x7f080008;
        public static final int server_password=0x7f080003;
        public static final int server_port=0x7f080002;
        public static final int server_quit=0x7f08000c;
        public static final int server_title=0x7f080000;
        public static final int server_usessl=0x7f080005;
        public static final int settings=0x7f08000a;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
        public static final int serveradd=0x7f030002;
        public static final int serveritem=0x7f030003;
        public static final int serverwindow=0x7f030004;
    }
    public static final class menu {
        public static final int main=0x7f070000;
        public static final int server=0x7f070001;
    }
    public static final class string {
        public static final int about_text=0x7f060004;
        public static final int about_title=0x7f060003;
        public static final int app_name=0x7f060000;
        public static final int server_add_title=0x7f060001;
        public static final int settings_title=0x7f060002;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
